default: &default
  adapter: mysql2

development:
  <<: *default
  database: materialize_apps_development
  username: username
  password: password

test:
  <<: *default
  database: materialize_apps_test
  username: username
  password: password

production:
  <<: *default
  database: materialize_apps_production
  username: materialize_apps
  password: <%= ENV['MATERIALIZE_APPS_DATABASE_PASSWORD'] %>
